import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/frontend/shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        <header className='w-full sticky top-0 z-50 bg-background shadow font-[family-name:var(--font-montserrat-sans)]'>
          <Navbar />
        </header>
        <main className='font-[family-name:var(--font-geist-sans)] min-h-screen'>
          {children}
        </main>
        <footer>
          <div className='container mx-auto px-4 py-8 text-center text-sm text-gray-500'>
            &copy; {new Date().getFullYear()} astzo. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
