import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Header from "@/components/frontend/shared/Navbar";

const montserrat = localFont({
  src: [
    {
      path: "../../../public/fonts/Montserrat-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Montserrat-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-montserrat",
});
export const metadata: Metadata = {
  title: "ASTZO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${montserrat.className} antialiased`}>
        <header className='w-full sticky top-0  bg-background border-b border-border'>
          <Header />
        </header>
        <main className='font-[family-name:var(--font-geist-sans)] min-h-screen'>
          {children}
        </main>
        <footer>
          <div className='container mx-auto px-4 py-8 text-center text-sm text-gray-500'>
            &copy; {new Date().getFullYear()} astzo. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
