import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='bg-destructive text-white py-4'>
          <div className='container mx-auto px-4'>
            <h1 className='text-2xl font-bold'>Welcome to astzo</h1>
          </div>
        </header>
        <main className='font-[family-name:var(--font-geist-sans)]'>
          {children}
        </main>
        <footer>
          <div className='container mx-auto px-4 py-8 text-center text-sm text-gray-500'>
            &copy; {new Date().getFullYear()} astzo. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
